[package]
name = "compile"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
aarch64 = []

[dependencies]
parity-wasm = { version = "0.42.2", default-features = false }